/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

import com.sun.org.apache.xpath.internal.operations.Variable;

/**
 *
 * @author alejozepol
 */
public class ventana extends javax.swing.JFrame {

    /**
     * Creates new form ventana
     */
    public ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Labels = new javax.swing.JPanel();
        nomN1 = new javax.swing.JLabel();
        nomN2 = new javax.swing.JLabel();
        nomN3 = new javax.swing.JLabel();
        Decimal = new javax.swing.JPanel();
        resultado = new javax.swing.JTextField();
        numero2 = new javax.swing.JTextField();
        numero1 = new javax.swing.JTextField();
        decimal = new javax.swing.JRadioButton();
        Binarios = new javax.swing.JPanel();
        b1 = new javax.swing.JTextField();
        b2 = new javax.swing.JTextField();
        rb = new javax.swing.JTextField();
        binario = new javax.swing.JRadioButton();
        Octal = new javax.swing.JPanel();
        o1 = new javax.swing.JTextField();
        o2 = new javax.swing.JTextField();
        ro = new javax.swing.JTextField();
        octal = new javax.swing.JRadioButton();
        Hexadecimal = new javax.swing.JPanel();
        nomh = new javax.swing.JLabel();
        h1 = new javax.swing.JTextField();
        h2 = new javax.swing.JTextField();
        rh = new javax.swing.JTextField();
        hexa = new javax.swing.JRadioButton();
        Operaciones = new javax.swing.JPanel();
        suma = new javax.swing.JButton();
        division = new javax.swing.JButton();
        multiplicacion = new javax.swing.JButton();
        resta = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Labels.setAlignmentX(0.2F);
        Labels.setAutoscrolls(true);

        nomN1.setText("Numero1");

        nomN2.setText("Numero 2");

        nomN3.setText("Resultado");

        javax.swing.GroupLayout LabelsLayout = new javax.swing.GroupLayout(Labels);
        Labels.setLayout(LabelsLayout);
        LabelsLayout.setHorizontalGroup(
            LabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LabelsLayout.createSequentialGroup()
                .addGroup(LabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LabelsLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(LabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomN3)
                            .addGroup(LabelsLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(nomN1))))
                    .addGroup(LabelsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nomN2)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        LabelsLayout.setVerticalGroup(
            LabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LabelsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nomN1)
                .addGap(18, 18, 18)
                .addComponent(nomN2)
                .addGap(11, 11, 11)
                .addComponent(nomN3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        buttonGroup1.add(decimal);
        decimal.setText("Decimal");
        decimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decimalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DecimalLayout = new javax.swing.GroupLayout(Decimal);
        Decimal.setLayout(DecimalLayout);
        DecimalLayout.setHorizontalGroup(
            DecimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DecimalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DecimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numero1)
                    .addComponent(numero2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(resultado, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(decimal, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        DecimalLayout.setVerticalGroup(
            DecimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DecimalLayout.createSequentialGroup()
                .addComponent(decimal, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonGroup1.add(binario);
        binario.setText("Binario");
        binario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BinariosLayout = new javax.swing.GroupLayout(Binarios);
        Binarios.setLayout(BinariosLayout);
        BinariosLayout.setHorizontalGroup(
            BinariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BinariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BinariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b1)
                    .addGroup(BinariosLayout.createSequentialGroup()
                        .addComponent(binario)
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addComponent(b2)
                    .addComponent(rb)))
        );
        BinariosLayout.setVerticalGroup(
            BinariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BinariosLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(binario, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonGroup1.add(octal);
        octal.setText("Octal");
        octal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                octalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OctalLayout = new javax.swing.GroupLayout(Octal);
        Octal.setLayout(OctalLayout);
        OctalLayout.setHorizontalGroup(
            OctalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(o1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(o2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(ro, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OctalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(octal, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addContainerGap())
        );
        OctalLayout.setVerticalGroup(
            OctalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OctalLayout.createSequentialGroup()
                .addComponent(octal, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(o1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(o2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );

        buttonGroup1.add(hexa);
        hexa.setText("Hexadecimal");
        hexa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hexaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HexadecimalLayout = new javax.swing.GroupLayout(Hexadecimal);
        Hexadecimal.setLayout(HexadecimalLayout);
        HexadecimalLayout.setHorizontalGroup(
            HexadecimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HexadecimalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HexadecimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HexadecimalLayout.createSequentialGroup()
                        .addComponent(hexa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(11, 11, 11))
                    .addComponent(h1)
                    .addComponent(h2)
                    .addComponent(rh)))
            .addGroup(HexadecimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HexadecimalLayout.createSequentialGroup()
                    .addContainerGap(96, Short.MAX_VALUE)
                    .addComponent(nomh)
                    .addContainerGap()))
        );
        HexadecimalLayout.setVerticalGroup(
            HexadecimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HexadecimalLayout.createSequentialGroup()
                .addComponent(hexa, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(h1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(h2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(rh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
            .addGroup(HexadecimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HexadecimalLayout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(nomh)
                    .addContainerGap(113, Short.MAX_VALUE)))
        );

        suma.setText("+");
        suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumaActionPerformed(evt);
            }
        });

        division.setText("-");
        division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisionActionPerformed(evt);
            }
        });

        multiplicacion.setText("*");
        multiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicacionActionPerformed(evt);
            }
        });

        resta.setText("/");
        resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaActionPerformed(evt);
            }
        });

        jButton5.setText("Limpliar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OperacionesLayout = new javax.swing.GroupLayout(Operaciones);
        Operaciones.setLayout(OperacionesLayout);
        OperacionesLayout.setHorizontalGroup(
            OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OperacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OperacionesLayout.createSequentialGroup()
                        .addComponent(suma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(division))
                    .addGroup(OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, OperacionesLayout.createSequentialGroup()
                            .addComponent(multiplicacion)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(resta))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        OperacionesLayout.setVerticalGroup(
            OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OperacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(suma)
                    .addComponent(division))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(multiplicacion)
                    .addComponent(resta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(Operaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Labels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(Decimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Binarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Hexadecimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Octal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Hexadecimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Octal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Decimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Binarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Labels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(Operaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumaActionPerformed

        if (decimal.isSelected() == true) {
            int num1 = Integer.parseInt(numero1.getText());
            int num2 = Integer.parseInt(numero2.getText());
            int br3;
            br3 = (num1 + num1);
            String bi1;
            String bi2;
            String bi3;
            String hr1;
            String hr2;
            String hr3;
            String oc1;
            String oc2;
            String oc3;

            bi1 = Integer.toBinaryString(num1);
            bi2 = Integer.toBinaryString(num2);
            bi3 = Integer.toBinaryString(br3);
            hr1 = Integer.toHexString(num1);
            hr2 = Integer.toHexString(num2);
            hr3 = Integer.toHexString(br3);
            oc1 = Integer.toOctalString(num1);
            oc2 = Integer.toOctalString(num2);
            oc3 = Integer.toOctalString(br3);

            resultado.setText(String.valueOf(br3));
            b1.setText(String.valueOf(bi1));
            b2.setText(String.valueOf(bi2));
            rb.setText(String.valueOf(bi3));
            h1.setText(String.valueOf(hr1));
            h2.setText(String.valueOf(hr2));
            rh.setText(String.valueOf(hr3));
            o1.setText(String.valueOf(oc1));
            o2.setText(String.valueOf(oc2));
            ro.setText(String.valueOf(oc3));

        }
        if (binario.isSelected() == true) {

            int bnum1 = Integer.parseInt(b1.getText());
            int dnum1 = Integer.parseInt(b1.getText(), 2);;
            int bnum2 = Integer.parseInt(b2.getText());
            int dnum2 = Integer.parseInt(b2.getText(), 2);;
            int dr = (dnum1+dnum1);
             resultado.setText(String.valueOf(dr));
//            int rd;
//                   rd =Integer.parseInt(dr.getText(), 2);; 
//                    Integer.toBinaryString(dr);   
          

            numero1.setText(String.valueOf(dnum1));
            numero2.setText(String.valueOf(dnum2));
           
//            rb.setText(String.valueOf(rd));
        }
        if (octal.isSelected() == true) {
            double onum1 = Double.parseDouble(o1.getText());
            double onum2 = Double.parseDouble(o2.getText());
            ro.setText(String.valueOf(onum1 + onum2));

        }

        if (hexa.isSelected() == true) {
            double hnum1 = Double.parseDouble(h1.getText());
            double hnum2 = Double.parseDouble(h2.getText());
            rh.setText(String.valueOf(hnum1 + hnum2));
        }
    }//GEN-LAST:event_sumaActionPerformed

    private void restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaActionPerformed
        double num1 = Double.parseDouble(numero1.getText());
        double num2 = Double.parseDouble(numero2.getText());
        resultado.setText(String.valueOf(num1 - num2));
    }//GEN-LAST:event_restaActionPerformed

    private void divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisionActionPerformed
        double num1 = Double.parseDouble(numero1.getText());
        double num2 = Double.parseDouble(numero2.getText());
        resultado.setText(String.valueOf(num1 / num2));
    }//GEN-LAST:event_divisionActionPerformed

    private void multiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicacionActionPerformed
        double num1 = Double.parseDouble(numero1.getText());
        double num2 = Double.parseDouble(numero2.getText());
        resultado.setText(String.valueOf(num1 / num2));
    }//GEN-LAST:event_multiplicacionActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        resultado.setText("");
        numero1.setText("");
        numero2.setText("");
        rb.setText("");
        b1.setText("");
        b2.setText("");
        o1.setText("");
        o2.setText("");
        ro.setText("");
        h1.setText("");
        h2.setText("");
        rh.setText("");
        buttonGroup1.clearSelection();

    }//GEN-LAST:event_jButton5ActionPerformed

    private void decimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimalActionPerformed
        b1.setText(String.valueOf(0));
        b2.setText(String.valueOf(0));
        o1.setText(String.valueOf(0));
        o2.setText(String.valueOf(0));
        h1.setText(String.valueOf(0));
        h2.setText(String.valueOf(0));
    }//GEN-LAST:event_decimalActionPerformed

    private void binarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binarioActionPerformed
        numero1.setText(String.valueOf(0));
        numero2.setText(String.valueOf(0));
        o1.setText(String.valueOf(0));
        o2.setText(String.valueOf(0));
        h1.setText(String.valueOf(0));
        h2.setText(String.valueOf(0));

    }//GEN-LAST:event_binarioActionPerformed

    private void hexaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hexaActionPerformed
        numero1.setText(String.valueOf(0));
        numero2.setText(String.valueOf(0));
        o1.setText(String.valueOf(0));
        o2.setText(String.valueOf(0));
        b1.setText(String.valueOf(0));
        b2.setText(String.valueOf(0));
    }//GEN-LAST:event_hexaActionPerformed

    private void octalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_octalActionPerformed
        numero1.setText(String.valueOf(0));
        numero2.setText(String.valueOf(0));
        h1.setText(String.valueOf(0));
        h2.setText(String.valueOf(0));
        b1.setText(String.valueOf(0));
        b2.setText(String.valueOf(0));
    }//GEN-LAST:event_octalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Binarios;
    private javax.swing.JPanel Decimal;
    private javax.swing.JPanel Hexadecimal;
    private javax.swing.JPanel Labels;
    private javax.swing.JPanel Octal;
    private javax.swing.JPanel Operaciones;
    private javax.swing.JTextField b1;
    private javax.swing.JTextField b2;
    private javax.swing.JRadioButton binario;
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JRadioButton decimal;
    private javax.swing.JButton division;
    private javax.swing.JTextField h1;
    private javax.swing.JTextField h2;
    private javax.swing.JRadioButton hexa;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton multiplicacion;
    private javax.swing.JLabel nomN1;
    private javax.swing.JLabel nomN2;
    private javax.swing.JLabel nomN3;
    private javax.swing.JLabel nomh;
    private javax.swing.JTextField numero1;
    private javax.swing.JTextField numero2;
    private javax.swing.JTextField o1;
    private javax.swing.JTextField o2;
    private javax.swing.JRadioButton octal;
    private javax.swing.JTextField rb;
    private javax.swing.JButton resta;
    private javax.swing.JTextField resultado;
    private javax.swing.JTextField rh;
    private javax.swing.JTextField ro;
    private javax.swing.JButton suma;
    // End of variables declaration//GEN-END:variables
}
